version: '3'

services:
  web:
    build: .
    working_dir: /home/python/app
    volumes:
    - "./WasteManagement:/home/python/app/WasteManagement"
    - "./Project_Database:/home/python/app/Project_Database"
    - "./PythonConfig/deploy_commands.sh:/deploy_commands.sh"
    - "./PythonConfig/requirements.txt:/requirements.txt"
    ports:
      - "8000:8000"
    command: 
       - /bin/bash
       - -c
       - |
        pip install -r /requirements.txt 
        echo "Starting django server ..."
        /deploy_commands.sh

